# Generated by Django 2.2.5 on 2019-11-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=264, unique=True)),
                ('lastname', models.CharField(max_length=264, unique=True)),
                ('email', models.URLField(unique=True)),
            ],
        ),
    ]
